spring:
  datasource:
    url: jdbc:mysql://192.168.13.106:3306/test-spring-boot?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:*Mapper.xml

yp:
  apiKey: bdd46e7c95fad7dfb71b58a5f0103f3f